In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

# any tuple,list in ndarray using array()

arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

#0-D array
arr = np.array(42)


print(arr.ndim)

print(type(arr))
#1-D array
arr = np.array([1, 2, 3, 4, 5])

print(arr.ndim)

print(type(arr))
#2-D array
arr = np.array([[1, 2, 3, 4],[3,4,5,6]])

print(arr.ndim)

print(type(arr))
#3-D array
arr = np.array([[[1, 2, 3],[1,2,3]],[[3,4,5],[3,4,6]]])

print(arr.ndim)

print(type(arr))

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
0
<class 'numpy.ndarray'>
1
<class 'numpy.ndarray'>
2
<class 'numpy.ndarray'>
3
<class 'numpy.ndarray'>
[[[[[1 2 3 4]]]]]
number of dimensions : 5
Last element from 2nd dim:  10


In [44]:
import numpy as np

#1

arr= np.array([1,2,3,4])
reversedarr= np.flip(arr)
print(reversedarr)

#2
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

flattened= np.ndarray.flatten(array1)
print(flattened)
print(array1.flatten())

#(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

compare= arr1==arr2
equal_arrays = compare.all()
 
print(equal_arrays)

#(d) Find the most frequent value and their indice(s) in the following arrays:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
freq=np.bincount(y)
value=max(freq)

for i in range(len(y)):
    if y[i]==value:
        print(y[i])

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("\nSum of arr : ", np.sum(gfg)) 
print("Sum of arr(axis = 0) : ", np.sum(gfg, axis = 0)) 
print("Sum of arr(axis = 1) : ", np.sum(gfg, axis = 1))

# A simple Python3 program to find
# sum of diagonals
MAX = 100
 
def printDiagonalSums(mat, n):
 
    principal = 0
    secondary = 0
    for i in range(0, n): 
        principal += mat[i][i]
        secondary += mat[i][n - i - 1]
         
    print("Principal Diagonal:", principal)
    print("Secondary Diagonal:", secondary)
    w, v = np.linalg.eig(mat) 
    print(w)
    print(v)
    print(np.linalg.inv(mat))
    print(np.linalg.det(mat))
    print("Shape of array:\n", np.shape(mat))

    print("Covariance matrix of x:\n", np.cov(mat))
 
# Driver code
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
printDiagonalSums(n_array, 3)

import numpy as np

p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]] 


# find out covariance with respect  rows
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("\nMatrices :") 
print("x =", x) 
print("\ny =", y) 
  
# Inner product of matrices 
print("\nInner product of matrices x and y =") 
print(np.inner(x, y)) 
print(np.outer(x, y)) 
print(np.cross(x, y)) 




[4 3 2 1]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]
True
3
3
3

Sum of arr :  45
Sum of arr(axis = 0) :  [[20  9 16]]
Sum of arr(axis = 1) :  [[14]
 [16]
 [15]]
Principal Diagonal: 176
Secondary Diagonal: 70
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001
Shape of array:
 (3, 3)
Covariance matrix of x:
 [[ 433.33333333  186.66666667 -663.33333333]
 [ 186.66666667  457.33333333 -452.66666667]
 [-663.33333333 -452.66666667 1089.33333333]]

Matrices :
x = [[2 3 4]
 [3 2 9]]

y = [[ 1  5  0]
 [ 5 10  3]]

Inner product of matrices x and y =
[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[-20   4   7]
 [-84  36  20]]


In [62]:
# Based on NumPy Mathematics and Statistics 
array = np.array([[1, -2, 3],[-4, 5, -6]])
array= array.flatten()

print(np.absolute(array))
print(np.percentile(array,25))
print(np.percentile(array,25))

print(np.percentile(array,50))
print(np.percentile(array,50))

print(np.percentile(array,75))
print(np.percentile(array,75))

print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.median(array))

a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))




[1 2 3 4 5 6]
-3.5
-3.5
-0.5
-0.5
2.5
2.5
-0.5
3.8622100754188224
14.916666666666666
-0.5
[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [22]:
#Q3: Based on Searching and Sorting
import numpy as np  
# array = np.array([10, 52, 62, 16, 16, 54, 453])

# #array.sort()
# b= np.argsort(array)
# print(b)

# small=4
# large=len(array)-5

# array.sort()
# print(array)
# print(array[:small])
# print(array[large:])

array = np.array([1.2, 1.2, 2.2, 2.3, 3.6, 2.1])

#integers only
x= np.where(np.mod(array,1)!=0)
x
#floats only


(array([0, 1, 2, 3, 4, 5], dtype=int64),)